version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5001:5000"
    volumes:
      - shared_uploads:/uploads  # Shared volume for audio files
    environment:
      - FLASK_ENV=development
    depends_on:
      - whisper

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"  # Vite dev server runs on port 5173
    volumes:
      - ./frontend:/app  # Mounts local frontend files for hot reloading
      - /app/node_modules  # Prevents overwriting node_modules inside Docker
    command: ["npm", "run", "dev", "--", "--host"]  # Run Vue in development mode
    depends_on:
      - backend

  whisper:
    build: ./whisper
    ports:
      - "6000:6000"
    volumes:
      - shared_uploads:/uploads  # Same shared volume as backend
    environment:
      - OPENAI_API_KEY=your_openai_api_key_here  # Replace with your actual API key
      - WHISPER_MODEL=base  # Options: tiny, base, small, medium, large
      - GPT_MODEL=gpt-4o-mini  # Options: gpt-4o-mini, gpt-4, etc.
      - GPT_TEMPERATURE=0.3  # Control randomness in translations (0.0-1.0)
    restart: always

volumes:
  shared_uploads:
